exports.NAME_MAP = {
  //"Afghanistan": "",
  //"Agalega & St. Brandon Is.": "",
  //"Aland Island": "",
  "Alaska": "USA", 
  "American Samoa": "Western Samoa",
  "Amsterdam & St. Paul Is.": "Netherlands",
  //"Andaman & Nicobar Island": "",
  //"Annobon Island": "",
  //"Antarctica": "",
  //"Ascension Island": "",
  //"Auckland & Campbell Is.": "",
  //"Austral Island": "",
  //"Aves Island": "",
  //"Azores": "",
  //"Baker & Howland Island": "",
  //"Balearic Island": "",
  //"Banaba Is. (Ocean Is.)": "",
  //"Bouvet Island": "",
  "Bonaire, Curacao. Netherlands Antilles": "?",
  "British Virgin Island": "Br. Virgin",
  //"Burundi": "",
  //"Cambodia": "",
  //"Canary Island": "",
  "Cayman Island": "Cayman Is.",
  //"Ceuta & Melilla": "",
  //"Chagos Island": "",
  //"Chatham Island": "",
  //"Chesterfield Island": "",
  //"Christmas Island": "",
  //"Clipperton Island": "",
  //"Cocos Island": "",
  //"Cocos-Keeling Island": "",
  "Congo (Republic of)": "DPR Congo",
  //"Conway Reef": "",
  //"Corsica": "",
  "Cote d’Ivoire": "Cote d'Ivoire",
  //"Crete": "",
  //"Crozet Island": "",
  "Czech Republic": "Czech Rep.",
  "Dem. People’s Rep. Korea": "?",
  "Dem. Rep. of Congo": "DPR Congo",
  "Dominican Republic": "Dominicana",
  //"Desecheo Island": "",
  //"Dodecanese": "",
  //"Ducie Island": "",
  //"Easter Island": "",
  "England": "UK",
  //"Eritrea": "",
  //"Falkland Island": "",
  "Faroe Islands": "Faroe Is.",
  //"Fernando de Noronha": "",
  //"Franz Josef Land": "",
  //"French Guiana": "",
  "French Polynesia": "Fr. Polynesia",
  //"Galapagos Island": "",
  //"Glorioso Island": "",
  //"Greenland": "",
  //"Guadeloupe": "",
  //"Guam": "",
  //"Guantanamo Bay": "",
  //"Guernsey": "",
  "Hawaii": "USA",
  //"Heard Island": "",
  //"Isle of Man": "",
  //"ITU HQ": "",
  //"Jan Mayen": "",
  //"Jersey": "",
  //"Johnston Island": "",
  //"Juan de Nova, Europa": "",
  //"Juan Fernandez Island": "",
  //"Kaliningrad": "",
  //"Kerguelen Island": "",
  //"Kermadec Island": "",
  //"Kingman Reef": "",
  //"Kure Island": "",
  //"Lakshadweep Island": "",
  //"Lord Howe lsland": "",
  //"Macao": "",
  "Macedonia": "FYR Macedonia",
  //"Macquarie Island": "",
  //"Madeira Island": "",
  //"Malpelo Island": "",
  //"Malyj Vysotskij Island": "",
  //"Mariana Island": "",
  //"Market Reef": "",
  //"Marquesas Island": "",
  "Marshall Island": "Marshall Is.",
  //"Martinique": "",
  //"Mayotte": "",
  //"Mellish Reef": "",
  //"Midway Island": "",
  //"Minami Torishima": "",
  //"Montenegro": "",
  //"Mount Athos": "",
  //"Myanmar": "",
  //"Navassa Island": "",
  //"Niger": "Nigeria",
  "Nigeria": "Nigeria",
  //"Niue": "",
  //"Norfolk Island": "",
  //"North Cook Islands": "",
  //"Ogasawara": "",
  //"Palau": "",
  //"Palestine": "",
  //"Palmyra & Jarvis Island": "",
  //"Peter I. Island": "",
  //"Pitcairn Island": "",
  //"Pratas Island": "",
  //"Prince Edward & Marion Is.": "",
  //"Puerto Rico": "",
  "Republic of Korea": "RO Korea",
  //"Reunion Island": "",
  //"Revillagigedo": "",
  //"Rodrigues Island": "",
  "Romania": "Romania",
  //"Rotuma Island": "",
  //"Sable Island": "",
  "Somalia": "?",
  "Samoa": "Western Samoa",
  //"San Andres & Providencia": "",
  //"San Felix & San Ambrosio": "",
  //"Sardinia": "",
  //"Scarborough Reef": "",
  "Scotland": "UK",
  //"Serbia": "",
  "Slovak Republic": "Slovakia",
  "Solomon Islands": "Solomon Is.",
  "Somalia": "?",
  //"South Cook Islands": "",
  //"South Orkney Island": "",
  //"South Sandwich Island": "",
  //"South Shetland Island": "",
  "South Georgia Island": "?",
  "Sov. Mil. Order of Malta": "?",
  //"Spratly Islands": "",
  //"St. Barthelemy Island.": "",
  //"St. Helena": "",
  //"St. Maarten, Saba, St. Eustatius": "",
  //"St. Martin": "",
  //"St. Paul Island": "",
  //"St. Peter & St. Paul Rocks": "",
  //"St. Pierre & Miquelon": "",
  //"Svalbard": "",
  //"Swain’s Island": "",
  "Taiwan": "Chinese Taipei",
  //"Temotu Province": "",
  //"Timor-Leste": "",
  //"Tokelau Island": "",
  //"Trindade & Martim Vaz Is.": "",
  //"Tristan da Cunha & Gough Is.": "",
  //"Tromelin Island": "",
  "United Arab Emirates": "UAE",
  //"United Nations HQ": "",
  "United States of America": "USA",
  "Virgin Island": "Br. Virgin",
  //"Wake Island": "",
  "Wales": "UK",
  //"Wallis & Futuna Island": "",
  //"Western Sahara": "",
  //"Willis Island": "",
  //"Yemen": "",
};